spring:
  datasource:
    url: jdbc:mariadb://localhost:7779/challympic
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: ssafy

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace